### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by a-teammate** [lasote/conan-sdl2_image#1]
Well it tells me to contact the author, since I'm trying to build on Windows.

Is windows support coming?

I see that the sdl2_image build procedure is pretty static.

So one clean way would be to add cmake/gn/gyp whatever support to SDL2_image or patch it using conan.
If you need building yourself (which you definitely do at least for non-C libs. I know you know) one could:  

1) upgrade the project (if newer than VS 2008)
2) replace the same stuff in the .vcxproj file (as you do in your build_with_make function
3) replace some more stuff since there is a VisualC/external folder containing includes..
4) build using the cli

Im probably telling you nothing new here.

P.S: Interchanging "Windows built" with Visual Studio is not fully correct ofc. MinGW support would require less headache, but some posix commands (namely the chmods) would need to go into if conditions

**Comment by lasote** [comment]
Hi, sdl2 ecosystem is complex, it requires time and I would need some help to support it...
Thanks for your tips, I hope to have time to achieve this, but any help is welcomed!

**Comment by lasote** [comment]
Hi @a-teammate . I've uploaded a new version with windows build enabled. It's a little preliminary but I've be able to build a package for VS14. Please, any feedback is welcome.

**Comment by a-teammate** [comment]
Wow youre fast, very nice thank you!

There are some linker problems left for me (VS14 update3 on win10 64bit, release)

> IMG_jpg.obj : error LNK2019: unresolved external symbol longjmp referenced in function
>  my_error_exit [C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\09d83
> b74fdc2115cd6498fea9d2c052627027a1c\SDL2_image-2.0.1\VisualC\SDL_image.vcxproj]
> IMG_png.obj : error LNK2001: unresolved external symbol longjmp [C:\Users\madoe.conan
> \data\SDL2_image\2.0.1\lasote\testing\build\09d83b74fdc2115cd6498fea9d2c052627027a1c\S
> DL2_image-2.0.1\VisualC\SDL_image.vcxproj]
> IMG_jpg.obj : error LNK2019: unresolved external symbol _setjmp referenced in function
>  IMG_LoadJPG_RW [C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\09d8
> 3b74fdc2115cd6498fea9d2c052627027a1c\SDL2_image-2.0.1\VisualC\SDL_image.vcxproj]
> IMG_png.obj : error LNK2001: unresolved external symbol _setjmp [C:\Users\madoe.conan
> \data\SDL2_image\2.0.1\lasote\testing\build\09d83b74fdc2115cd6498fea9d2c052627027a1c\S
> DL2_image-2.0.1\VisualC\SDL_image.vcxproj]
> MSVCRT.lib(_setjmp.obj) : error LNK2001: unresolved external symbol _setjmp [C:\Users\
> madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\09d83b74fdc2115cd6498fea9d2c05
> 2627027a1c\SDL2_image-2.0.1\VisualC\SDL_image.vcxproj]
> MSVCRT.lib(_setjmp.obj) : error LNK2001: unresolved external symbol __intrinsic_setjmp
>  [C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\09d83b74fdc2115cd64
> 98fea9d2c052627027a1c\SDL2_image-2.0.1\VisualC\SDL_image.vcxproj]
> C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\09d83b74fdc2115cd6498
> fea9d2c052627027a1c\SDL2_image-2.0.1\VisualC\x64\Release\SDL2_image.dll : fatal error
>  LNK1120: 3 unresolved externals [C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\t
> esting\build\09d83b74fdc2115cd6498fea9d2c052627027a1c\SDL2_image-2.0.1\VisualC\SDL_ima
> ge.vcxproj]

Edit:

Some research suggested it could be because of the runtime linkage? (See https://msdn.microsoft.com/en-us/library/aa272905(v=vs.60).aspx ) Theres also [this](https://github.com/residualvm/residualvm/blob/master/backends/platform/sdl/sdl-sys.h#L63) but i doubt that is really clean what they're doing, and [this](https://github.com/modula3/cm3/issues/8)).

Maybe the fault is on my side then?
I build with `conan install .. --build` without further args (after downloading and installing nasm for windows, otherwise libjpeg-turbo fails to build).
I tried with options
  SDL2_image:shared=True
  SDL2:shared=True
and both set to False as well.

**Comment by a-teammate** [comment]
Ok I resolved those issues, its very much described here: http://stackoverflow.com/questions/31527969/how-to-i-update-my-c-project-in-visual-studio-2015-to-use-the-new-universal-cr

new issues are:

> "C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\5b5aee56e0d9082fafc8
> ea6e4ec7f702abf4f3b8\SDL2_image-2.0.1\VisualC\SDL_image.sln" (SDL2_image Ziel) (1) ->
> "C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\5b5aee56e0d9082fafc8
> ea6e4ec7f702abf4f3b8\SDL2_image-2.0.1\VisualC\SDL_image.vcxproj" (Standardziel) (2) ->
> (Link Ziel) ->
>   SDL2.lib(SDL.obj) : error LNK2005: _DllMainCRTStartup already defined in msvcrt.lib(
> dll_dllmain.obj) [C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\5b5
> aee56e0d9082fafc8ea6e4ec7f702abf4f3b8\SDL2_image-2.0.1\VisualC\SDL_image.vcxproj]
>   C:\Users\madoe.conan\data\SDL2_image\2.0.1\lasote\testing\build\5b5aee56e0d9082fafc
> 8ea6e4ec7f702abf4f3b8\SDL2_image-2.0.1\VisualC\x64\Release\SDL2_image.dll : fatal err
> or LNK1169: one or more multiply defined symbols found [C:\Users\madoe.conan\data\SDL
> 2_image\2.0.1\lasote\testing\build\5b5aee56e0d9082fafc8ea6e4ec7f702abf4f3b8\SDL2_image
> -2.0.1\VisualC\SDL_image.vcxproj]

These errors look familiar though.. If I just knew how i had resolved them ^^
maybe the subsystem entry? maybe /clr ? or intermixed MD MT stuff.. I'll check

Besides/**Off-Topic**:

I didnt quite understand how to change between MT and MD for conan. Is there a way to specify this globally in a conanfile.py for all dependencies? Ive adjusted .conan/conan.conf, but SDL2 is still compiling with /MD. Do you override it for a reason? And furthermore does that mean I have to built every lib with /MD?
**EDIT:** I mean even if I modify my settings.yml and remove any MD option if I try to `conan install .. --build=missing -s settings.compiler.runtime=MT -s compiler.runtime=MT` it just errors with

> ERROR: 'MD' is not a valid 'settings.compiler.runtime' value

**EDIT2:** Same error with `conan test -s arch=x86_64 -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime=MT --build` and a modified settings.yml..

Even more Off-Topic:
Furthermore is there a link-time-code generation switch (so I can say: hey I want everything in static libs for modularity, but combine them the best you can into one giant perfectly optimized executable) and a debug format switch ( /Zi vs /Z7, while i think they are not compatible as well between builds) or do these need to be added to each library before?

**Comment by lasote** [comment]
Hi!

Usually you can specify the runtime with `-s compiler="Visual Studio" -s compiler.runtime=MT` (The second line you wrote should work!)

But there is no dark magic behind conan, the SDL2_image recipe has to take care of invoke the compilation using the selected runtime (-s compiler.runtime), but with SDL2_image I have no CMakeLists.txt (or autotools for linux, or any other build system) to really control the runtime that will be used.
I only have a visual project  and the "msbuild" tool. I don't know too much about Visual Studio but it seems that you can generate multiple "targets" and selecting the runtime to be usen in each one. Then you can invoke "msbuild" to select which one has to be compiled. right? I think in the SDL2_image default project there is only one target for the library called SDL2_image and I don't know what runtime is using. Maybe could we generate a new visual project and patch the original? This way we could prepare an alternative project with several targets for each runtime and with the conan recipe select the right one according to the _compiler.runtime_ setting.
Another possibility is to find (or program) a CMakeLists.txt to compile the SDL2_image. With conan + CMake the runtime management is automatic.

**About the Universal CRT** we don't have enough experience yet with that, but maybe we need to add to default setting values the UCRT o something like that in addition to MD, MT, MDd, MTd etc. We still don't know if we can control it with CMake easily etc... a GREAT to-do. Any help or clarification would be very welcomed.

**About the "Even more Off-Topic"**
As I said, there is no magic behind conan. The static/shared capability depends on each library recipe. I usually try to support static and shared libraries in my recipes. But "shared" is an option, not a setting, because it's not a global thing. You could need a shared library with embedded static libraries.  Is that means that you cannot do the things you mention with conan? No, you can do it, but maybe you need to write your own recipes with the options that you need and control the building yourself to manage the debug levels etc.

**Comment by a-teammate** [comment]
Okay, since SDL2_image is a pretty stable project adding a CMakeLists.txt seems like the easiest option to me. The alternative to replace all defines of "MD" with "MT" in the visual studio project file (its a usual xml file) seems like the uglier approach to me, what do you say?

Otherwise I'll write the CMakeLists.txt tomorrow, that will be no problem i guess.

**Off-Topic**: I'll start a new pad the next days, something like "Package Creator Good Practices" (My knowledge is mostly windows-based in that topic though) where I'll try to summarize a few basic points about that stuff. Since I don't know about any blog or page having summarized what needs to be done for a clean dependency managment (If you do, plz hint it to me)
Maybe we could reflect that in the new-project conanfile.py templates then as well.

**Comment by lasote** [comment]
If you can program a CMakeLists.txt would be great! Any help you need just write. I can help you to apply the CMakeLists to the recipe and test it with multiple configurations.

**Comment by a-teammate** [comment]
Its tested and working :)
